# **Link tham khảo**  
Bài này được tham khảo từ medium: https://achimoraites.medium.com/fine-tuning-roberta-for-topic-classification-with-hugging-face-transformers-and-datasets-library-c6f8432d0820  
Notebook cũng được đẩy lên github: https://github.com/achimoraites/machine-learning-playground/blob/main/NLP/Text%20classification/RoBERTa_Finetuning.ipynb


# **Bắt đầu code**

In [1]:
! pip install git+https://github.com/huggingface/peft

  Cloning https://github.com/huggingface/peft to /tmp/pip-req-build-0d0yljpn
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft /tmp/pip-req-build-0d0yljpn
  Resolved https://github.com/huggingface/peft to commit 6d458b300fc2ed82e19f796b53af4c97d03ea604
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.5/450.5 kB 8.8 MB/s eta 0:00:00
  Created wheel for peft: filename=peft-0.14.1.dev0-py3-none-any.whl size=381416 sha256=5e5eeed96044bcffa34ec7f0bc3944b078a418c8f2b3b3e211e3e9c16c713e69
  Stored in directory: /tmp/pip-ephem-wheel-cache-v9v8bb34/wheels/4c/16/67/1002a2d4daa822eff130e6d85b90051b75d2ce0d26b9448e4a
Successfully built peft
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.24.7
    Uninstalling huggingface-hub-0.24.7:
      Successfully uninstalled huggingface-hub-0.24

In [2]:
### Import các thư viện cần thiết
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    RobertaForSequenceClassification,
    BertForSequenceClassification,
    TrainingArguments,
    Trainer,
    AutoConfig,
    EvalPrediction
)
from peft import LoraConfig, get_peft_model, PeftType
from huggingface_hub import HfFolder, login
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device # thật ra code này không dùng đến device

'cuda'

In [4]:
### Đăng nhập vào Huggingface
# có thể không cần thiết phải đăng nhập (?) chỉ cần truyền token vào khi gọi hàm model.push_to_hub() là được
login(token = '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') # phải cung cấp 1 cái token của HF 

## **CONFIG**

In [5]:
# FacebookAI/roberta-base; FacebookAI/roberta-large
# cardiffnlp/twitter-roberta-base; cardiffnlp/twitter-roberta-large-2022-154m
# Twitter/twhin-bert-base; Twitter/twhin-bert-large
'''đặt tên repo trên huggingface
prj-web-mining_LORA_{tên model}_{full-train hoặc sample-train}
'''
model_id = "cardiffnlp/twitter-roberta-base"  # tên huggingface của pretrained model, kéo về để đi finetune 
sampling_ratio = 1 # 0.0001 có sample tập train để thành tập train bé hơn không? # Note: để = 1 nếu không sample
num_epoch = 5

if sampling_ratio == 1:
    repository_id = f"shao2011/prj-web-mining_LORA_{model_id.split('/')[1]}_full-train" # tên huggingface để up checkpoint của model lên sau khi finetune xong
else:
    repository_id = f"shao2011/prj-web-mining_LORA_{model_id.split('/')[1]}_sample-train" # tên huggingface để up checkpoint của model lên sau khi finetune xong


# Các path của các file dataset
train_csv = '/kaggle/input/data-project-web-mining-2024-1/train/train.csv'
val_text_txt = '/kaggle/input/data-project-web-mining-2024-1/val/val_text.txt'
val_label_txt = '/kaggle/input/data-project-web-mining-2024-1/val/val_labels.txt'
test_text_txt = '/kaggle/input/data-project-web-mining-2024-1/test/test_text.txt'
test_label_txt = '/kaggle/input/data-project-web-mining-2024-1/test/test_labels.txt'

# file mapping (id, emoji, label)
mapping_txt = '/kaggle/input/data-project-web-mining-2024-1/mapping.txt'

print(model_id)
print(repository_id)

cardiffnlp/twitter-roberta-base
shao2011/prj-web-mining_LORA_twitter-roberta-base_full-train


## **Load dataset (chuẩn bị dataset)**  
dataset phải là của class datasets.Dataset (chứ không phải Dataset của pytorch nhé)

In [6]:
with open(mapping_txt, 'r') as f:
    lines = f.read().splitlines()
    lines = [line.split('\t') for line in lines]
    id2label = {int(line[0]): line[2] for line in lines}
    label2emoji = {line[2]: line[1] for line in lines}

# Hàm tính phân phối của các class trong 1 tập train/val/test -> để kiểm tra xem tập train có mất cân bằng dữ liệu không
def class_distributtion(dataset: Dataset, id2label: dict = id2label):
    count = dict()
    for i in range(len(dataset)):
        label = id2label[dataset[i]['label']] #note: dataset[i]['label'] là cái id, là số (còn label là string)
        if label not in count:
            count[label] = 0
        count[label] += 1

    total = len(dataset)
    for label in count:
        count[label] = round(count[label]/total*100,2)
        print(f"{label}: {count[label]} %")
        
    return count

In [7]:
# Tạo dataset của tập train
df = pd.read_csv(train_csv)
train_dataset = Dataset.from_dict({
    'text': df['sentence'].to_list(),
    'label': df['label'].to_list()
})
print(train_dataset)
print(train_dataset[0])
print(train_dataset[1])
print(class_distributtion(train_dataset))

Dataset({
    features: ['text', 'label'],
    num_rows: 454020
})
{'text': 'LoL @ West Covina, California', 'label': 2}
{'text': 'Things got a little festive at the office #christmas2016 @ RedRock…', 'label': 17}
_face_with_tears_of_joy_: 10.31 %
_Christmas_tree_: 2.59 %
_red_heart_: 21.65 %
_camera_with_flash_: 2.72 %
_smiling_face_with_hearteyes_: 10.51 %
_face_blowing_a_kiss_: 3.27 %
_blue_heart_: 3.38 %
_purple_heart_: 2.58 %
_sun_: 2.79 %
_two_hearts_: 5.38 %
_smiling_face_with_smiling_eyes_: 4.72 %
_winking_face_: 2.74 %
_beaming_face_with_smiling_eyes_: 2.66 %
_camera_: 3.3 %
_fire_: 5.04 %
_smiling_face_with_sunglasses_: 4.36 %
_hundred_points_: 2.73 %
_sparkles_: 3.67 %
_United_States_: 3.08 %
_winking_face_with_tongue_: 2.5 %
{'_face_with_tears_of_joy_': 10.31, '_Christmas_tree_': 2.59, '_red_heart_': 21.65, '_camera_with_flash_': 2.72, '_smiling_face_with_hearteyes_': 10.51, '_face_blowing_a_kiss_': 3.27, '_blue_heart_': 3.38, '_purple_heart_': 2.58, '_sun_': 2.79, '_two_he

In [8]:
# Tạo dataset của tập val
with open(val_text_txt, 'r') as f:
    val_text = f.read().splitlines()
with open(val_label_txt, 'r') as f:
    val_label = [int(i) for i in f.read().splitlines()]
    
val_dataset = Dataset.from_dict({
    'text': val_text,
    'label': val_label
})
print(val_dataset)
print(val_dataset[0])
print(val_dataset[1])
print(class_distributtion(val_dataset))

Dataset({
    features: ['text', 'label'],
    num_rows: 5000
})
{'text': 'A little throwback with my favourite person @ Water Wall', 'label': 0}
{'text': 'glam on @user yesterday for #kcon makeup using @user in #featherette,…', 'label': 7}
_red_heart_: 21.12 %
_sparkles_: 3.98 %
_United_States_: 2.86 %
_face_with_tears_of_joy_: 10.08 %
_smiling_face_with_hearteyes_: 10.42 %
_blue_heart_: 3.54 %
_purple_heart_: 3.06 %
_face_blowing_a_kiss_: 3.42 %
_beaming_face_with_smiling_eyes_: 2.74 %
_winking_face_with_tongue_: 2.62 %
_fire_: 4.86 %
_smiling_face_with_sunglasses_: 4.08 %
_winking_face_: 2.58 %
_smiling_face_with_smiling_eyes_: 4.76 %
_camera_: 3.18 %
_hundred_points_: 2.96 %
_two_hearts_: 6.16 %
_sun_: 2.58 %
_Christmas_tree_: 2.42 %
_camera_with_flash_: 2.58 %
{'_red_heart_': 21.12, '_sparkles_': 3.98, '_United_States_': 2.86, '_face_with_tears_of_joy_': 10.08, '_smiling_face_with_hearteyes_': 10.42, '_blue_heart_': 3.54, '_purple_heart_': 3.06, '_face_blowing_a_kiss_': 3.42, '_be

In [9]:
# Tạo dataset của tập test
with open(test_text_txt, 'r') as f:
    test_text = f.read().splitlines()
with open(test_label_txt, 'r') as f:
    test_label = [int(i) for i in f.read().splitlines()]
    
test_dataset = Dataset.from_dict({
    'text': test_text,
    'label': test_label
})
print(test_dataset)
print(test_dataset[0])
print(test_dataset[1])
print(class_distributtion(test_dataset))

Dataset({
    features: ['text', 'label'],
    num_rows: 50000
})
{'text': 'en Pelham Parkway', 'label': 2}
{'text': 'The calm before...... | w/ sofarsounds @user | : B. Hall.......#sofarsounds…', 'label': 10}
_face_with_tears_of_joy_: 9.07 %
_camera_: 2.86 %
_smiling_face_with_sunglasses_: 3.99 %
_smiling_face_with_hearteyes_: 9.66 %
_beaming_face_with_smiling_eyes_: 2.31 %
_Christmas_tree_: 3.09 %
_fire_: 7.43 %
_sun_: 2.53 %
_camera_with_flash_: 4.83 %
_red_heart_: 21.6 %
_smiling_face_with_smiling_eyes_: 3.23 %
_sparkles_: 5.5 %
_winking_face_: 2.61 %
_two_hearts_: 5.21 %
_purple_heart_: 2.23 %
_United_States_: 3.9 %
_blue_heart_: 3.1 %
_face_blowing_a_kiss_: 2.35 %
_hundred_points_: 2.49 %
_winking_face_with_tongue_: 2.02 %
{'_face_with_tears_of_joy_': 9.07, '_camera_': 2.86, '_smiling_face_with_sunglasses_': 3.99, '_smiling_face_with_hearteyes_': 9.66, '_beaming_face_with_smiling_eyes_': 2.31, '_Christmas_tree_': 3.09, '_fire_': 7.43, '_sun_': 2.53, '_camera_with_flash_': 4.83, '

In [10]:
# giải phóng bộ nhớ
df = None
val_text = None
val_label = None
test_text = None
test_label = None

### **Sample tập train nhỏ hơn**

In [11]:
# sample tập train nhỏ hơn
train_dataset = train_dataset.shuffle().select(range(int(sampling_ratio * len(train_dataset))))
print(train_dataset)
print(class_distributtion(train_dataset))

Dataset({
    features: ['text', 'label'],
    num_rows: 454020
})
_United_States_: 3.08 %
_two_hearts_: 5.38 %
_camera_with_flash_: 2.72 %
_Christmas_tree_: 2.59 %
_face_with_tears_of_joy_: 10.31 %
_blue_heart_: 3.38 %
_red_heart_: 21.65 %
_smiling_face_with_hearteyes_: 10.51 %
_smiling_face_with_smiling_eyes_: 4.72 %
_sun_: 2.79 %
_fire_: 5.04 %
_camera_: 3.3 %
_winking_face_: 2.74 %
_sparkles_: 3.67 %
_beaming_face_with_smiling_eyes_: 2.66 %
_purple_heart_: 2.58 %
_hundred_points_: 2.73 %
_winking_face_with_tongue_: 2.5 %
_face_blowing_a_kiss_: 3.27 %
_smiling_face_with_sunglasses_: 4.36 %
{'_United_States_': 3.08, '_two_hearts_': 5.38, '_camera_with_flash_': 2.72, '_Christmas_tree_': 2.59, '_face_with_tears_of_joy_': 10.31, '_blue_heart_': 3.38, '_red_heart_': 21.65, '_smiling_face_with_hearteyes_': 10.51, '_smiling_face_with_smiling_eyes_': 4.72, '_sun_': 2.79, '_fire_': 5.04, '_camera_': 3.3, '_winking_face_': 2.74, '_sparkles_': 3.67, '_beaming_face_with_smiling_eyes_': 2.66, '_

## **Preprocessing**

### Tokenize các câu (sentence) bằng Tokenizer của model pretrained

In [12]:
# Load lại tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id) # để sẵn: model = AutoModelForMaskedLM.from_pretrained("FacebookAI/roberta-base")

# Hàm tokenize: hàm này sử dụng cái Tokenizer của Roberata để tokenize cho các câu (biến mỗi một câu thành các token)
# Nó sẽ padding nếu câu ngắn hơn 256 và nó sẽ truncate (cắt xén) nếu câu dài hơn 256; 256 là cái max_length truyền vào.
def tokenize(batch):
    return tokenizer(batch["text"], padding=True, truncation=True)

config.json:   0%|          | 0.00/565 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [13]:
train_dataset = train_dataset.map(tokenize, batched=True, batch_size= len(train_dataset))
val_dataset = val_dataset.map(tokenize, batched=True, batch_size= len(val_dataset))
test_dataset = test_dataset.map(tokenize, batched=True, batch_size= len(test_dataset))

# print(train_dataset)
# print(val_dataset)
# print(test_dataset)

Map:   0%|          | 0/454020 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [14]:
print(train_dataset)
print(val_dataset)
print(test_dataset)

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 454020
})
Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 5000
})
Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 50000
})


### Set dataset format

In [15]:
# Set dataset format
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

train_dataset[0] # kiểm tra xem các array 'input_ids' và 'attention_mask' có phải torch.tensor không ?

{'label': tensor(11),
 'input_ids': tensor([    0, 12583,  3627,   328,   849,   329,   783,   605,  3967,   849,
           282, 19909,   849, 42952,  3583,   849, 13253,   849, 13253,   787,
          2848,     9,  4766,     2,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,  

## **Xác định Cấu Hình cho LoRA**

In [16]:
'''
# Tạo object Config, nó biểu diễn cấu hình của model
config = AutoConfig.from_pretrained(model_id) # lấy cấu hình của model pretrained luôn (vào cái pretrained model trên HF: https://huggingface.co/FacebookAI/roberta-base/tree/main, rồi vào tab files and versions, rồi vào file config.json sẽ thấy)

# thêm cái id2label để phục vụ cho việc cấu hình các khía cạnh liên quan đến số class phân loại. 
# (nếu ko có, thì mặc định sẽ là binary classification)
config.update({'id2label': id2label}) # Phải đặt tên là id2label thì mới nhận diện được đây là các class output ra. 
print(config)
'''

# Define LoRA configuration
lora_config = LoraConfig(
    peft_type=PeftType.LORA, # có thể bỏ dòng này ?
    task_type="SEQ_CLS",  # Sequence classification
    r=16,                 # LoRA rank
    lora_alpha=32,        # Scaling factor
    lora_dropout=0.1      # Dropout rate
)

## **Tạo model và Load model**
- Cái cấu hình (config) được truyền vào để cấu hình lại model được tạo ra (ví dụ: `architecture` được dùng là gì, `hàm activate` là relu hay gelu, `id2label` như nào để còn tạo số nơ-ron của layer cuối trong bộ classifier, ...)
- Còn cái string "FacebookAI/roberta-base" chỉ là được dùng để xác định chỗ load trọng số pretrained thôi. (các trọng số pretrained sẽ được lấy giá trị từ cái checkpoint/repo tên là "FacebookAI/roberta-base").  


In [17]:
'''model = RobertaForSequenceClassification.from_pretrained(model_id, config = config)'''

# Tạo model
if 'bert' in set(model_id.split('/')[1].split("-")):
    model = BertForSequenceClassification.from_pretrained(model_id, id2label = id2label)
else:
    model = RobertaForSequenceClassification.from_pretrained(model_id, id2label = id2label)
print('bert' in set(model_id.split('/')[1].split("-")))

# Apply cái cấu hình Lora vào model để cấu hình lại model. (freeze 1 số layer, ...)
model = get_peft_model(model, lora_config)

print(model) # để ý: trong cái lớp (layer) out_proj xem cái out_features có = số class (= 20) không ?
print('\n')
print(model.print_trainable_parameters())

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at cardiffnlp/twitter-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


False
PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): RobertaForSequenceClassification(
      (roberta): RobertaModel(
        (embeddings): RobertaEmbeddings(
          (word_embeddings): Embedding(50265, 768, padding_idx=1)
          (position_embeddings): Embedding(514, 768, padding_idx=1)
          (token_type_embeddings): Embedding(1, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): RobertaEncoder(
          (layer): ModuleList(
            (0-11): 12 x RobertaLayer(
              (attention): RobertaAttention(
                (self): RobertaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): M

## **Train model**

### Tạo Training Arguments và Trainer để train và cả evaluate model luôn
link doc của class Trainer: https://huggingface.co/docs/transformers/main_classes/trainer

In [18]:
def macro_average_f1_score(evalPrediction: EvalPrediction):
    pred = np.argmax(evalPrediction.predictions, axis = 1)
    print(len(pred))
    print(pred)
    gold = list(evalPrediction.label_ids)
    
    report = classification_report(gold, pred, output_dict=True)
    f1_score = report['macro avg']['f1-score'] 
    acc_score = report['accuracy']
    return {'macro avg F1': f1_score, 'accuracy': acc_score}

In [19]:
# TrainingArguments
training_args = TrainingArguments(
    output_dir=repository_id,
    
    num_train_epochs= num_epoch,
    learning_rate=5e-5,
    weight_decay=0.01,
    warmup_steps=500,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    
    evaluation_strategy="epoch",
    logging_dir=f"{repository_id}/logs",
    logging_strategy="steps",
    logging_steps=10,
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model = 'macro avg F1',
    save_total_limit=1,
    report_to="tensorboard",

    push_to_hub=True,
    hub_strategy="every_save",
    hub_model_id=repository_id,
    hub_token=HfFolder.get_token(),
    
    tpu_num_cores = 8 # dùng TPU
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics = macro_average_f1_score
)

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [20]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


5000
[ 3  7 11 ... 15  2  1]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


5000
[ 3  7 11 ...  2  2  1]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


5000
[ 3  7 11 ... 15  2  1]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


5000
[ 3  7 11 ...  2  2  1]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


5000
[ 3  7 11 ...  2  2  1]


TrainOutput(global_step=70945, training_loss=1.6983748901889293, metrics={'train_runtime': 41193.3024, 'train_samples_per_second': 55.108, 'train_steps_per_second': 1.722, 'total_flos': 2.54356806686472e+17, 'train_loss': 1.6983748901889293, 'epoch': 5.0})

In [21]:
test_result = trainer.evaluate(eval_dataset=test_dataset)
print("Kết quả eval trên test set")
for k in test_result:
    print(f"{k}: {test_result[k]}")

/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


50000
[ 1 10  7 ...  1  0  2]
Kết quả eval trên test set
eval_loss: 1.5948748588562012
eval_macro avg F1: 0.3559067437709117
eval_accuracy: 0.50052
eval_runtime: 375.146
eval_samples_per_second: 133.281
eval_steps_per_second: 4.166
epoch: 5.0
